cmake_minimum_required(VERSION 3.22.1)
project(zip LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(ZLIB_COMPAT ON CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(WITH_GTEST OFF CACHE BOOL "" FORCE)
set(WITH_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(WITH_FUZZERS OFF CACHE BOOL "" FORCE)
set(ENABLE_COMMONCRYPTO OFF CACHE BOOL "" FORCE)
set(ENABLE_GNUTLS OFF CACHE BOOL "" FORCE)
set(ENABLE_OPENSSL OFF CACHE BOOL "" FORCE)
set(ENABLE_WINDOWS_CRYPTO OFF CACHE BOOL "" FORCE)
set(ENABLE_BZIP2 OFF CACHE BOOL "" FORCE)
set(ENABLE_LZMA OFF CACHE BOOL "" FORCE)
set(ENABLE_ZSTD OFF CACHE BOOL "" FORCE)
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(BUILD_REGRESS OFF CACHE BOOL "" FORCE)
set(BUILD_OSSFUZZ OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_DOC OFF CACHE BOOL "" FORCE)
set(LIBZIP_DO_INSTALL OFF CACHE BOOL "" FORCE)

add_subdirectory(lib/zlib-ng)
add_library(ZLIB::ZLIB ALIAS zlib-ng)
add_subdirectory(lib/libzip)

add_library(kernel_zip SHARED native-lib.cpp)
set_target_properties(kernel_zip PROPERTIES OUTPUT_NAME zip)
target_include_directories(kernel_zip PRIVATE lib/libzip/lib ${CMAKE_CURRENT_BINARY_DIR}/libzip)
target_link_libraries(kernel_zip PRIVATE libzip::zip)
target_compile_options(kernel_zip PRIVATE -O3 -DNDEBUG -fvisibility=hidden -ffunction-sections -fdata-sections)
target_link_options(kernel_zip PRIVATE -Wl,--gc-sections -Wl,--exclude-libs,ALL)
