module;
#include <cstdint>
#include <charconv>
#include <string_view>
export module tool.popcap.texture.ptx.ptx_types;
export {
namespace PtxUtils {
inline constexpr uint32_t PTX_MAGIC = 0x70747831u;
inline constexpr uint32_t VERSION = 1u;
struct PtxHeader { uint32_t magic = PTX_MAGIC; uint32_t version = VERSION; uint32_t width = 0; uint32_t height = 0; uint32_t pitch = 0; uint32_t format = 0; uint32_t alphaSize = 0; uint32_t alphaFormat = 0; };
}
namespace ImagePtxCodec {
enum class AlphaScheme : uint8_t { None, A8, A8_A1, Palette4_A1, Palette5_A1 };
enum class Tag : uint8_t { ARGB8888, ABGR8888, RGBA4444, RGB565, RGBA5551, RGBA4444_Block, RGB565_Block, RGBA5551_Block, XRGB8888_AuxAlpha, XBGR8888_AuxAlpha, ARGB8888_BE, ARGB8888_Padding_BE, DXT1_RGB, DXT3_RGBA, DXT5_RGBA, DXT5_RGBA_MortonBlock, DXT5_RGBA_BE, ETC1_RGB, PVRTC_4BPP_RGBA, PVRTC_2BPP_RGBA, ASTC_4x4, ASTC_5x5, ASTC_6x6, ASTC_8x8 };
struct FormatSpec { Tag tag = Tag::ARGB8888; uint32_t fileId = 0; AlphaScheme alpha = AlphaScheme::None; bool headerBigEndian = false; bool markAlpha64 = false; bool valid = true; };
[[nodiscard]] inline bool isAuxFileId(uint32_t id) noexcept { return id >= 147u && id <= 150u; }
[[nodiscard]] inline bool isAstcFileId(uint32_t id) noexcept { return id >= 160u && id <= 163u; }
[[nodiscard]] inline FormatSpec makeSimple(Tag tag, uint32_t id, bool be = false, bool mark64 = false) noexcept { return {tag, id, AlphaScheme::None, be, mark64, true}; }
[[nodiscard]] inline FormatSpec makeAux(Tag tag, uint32_t id, AlphaScheme alpha, bool mark64 = false) noexcept { return {tag, id, alpha, false, mark64, true}; }
[[nodiscard]] inline FormatSpec invalidSpec() noexcept { FormatSpec s{}; s.valid = false; return s; }
[[nodiscard]] inline FormatSpec parseFormatStr(std::string_view f) {
 if (f == "ARGB8888") return makeSimple(Tag::ARGB8888, 0); if (f == "ABGR8888") return makeSimple(Tag::ABGR8888, 0); if (f == "RGBA4444") return makeSimple(Tag::RGBA4444, 1); if (f == "RGB565") return makeSimple(Tag::RGB565, 2); if (f == "RGBA5551") return makeSimple(Tag::RGBA5551, 3); if (f == "RGBA4444_Block") return makeSimple(Tag::RGBA4444_Block, 21); if (f == "RGB565_Block") return makeSimple(Tag::RGB565_Block, 22); if (f == "RGBA5551_Block") return makeSimple(Tag::RGBA5551_Block, 23); if (f == "XRGB8888_A8") return makeAux(Tag::XRGB8888_AuxAlpha, 149, AlphaScheme::A8); if (f == "XBGR8888_A8") return makeAux(Tag::XBGR8888_AuxAlpha, 149, AlphaScheme::A8); if (f == "XRGB8888_A_Palette") return makeAux(Tag::XRGB8888_AuxAlpha, 149, AlphaScheme::Palette4_A1, true); if (f == "XBGR8888_A_Palette") return makeAux(Tag::XBGR8888_AuxAlpha, 149, AlphaScheme::Palette4_A1, true); if (f == "ARGB8888_BE" || f == "ARGB8888(BE)") return makeSimple(Tag::ARGB8888_BE, 0, true); if (f == "ARGB8888_Padding_BE" || f == "ARGB8888_Padding(BE)") return makeSimple(Tag::ARGB8888_Padding_BE, 0, true); if (f == "DXT1_RGB") return makeSimple(Tag::DXT1_RGB, 35); if (f == "DXT3_RGBA") return makeSimple(Tag::DXT3_RGBA, 36); if (f == "DXT5_RGBA") return makeSimple(Tag::DXT5_RGBA, 37); if (f == "DXT5_RGBA_MortonBlock") return makeSimple(Tag::DXT5_RGBA_MortonBlock, 5); if (f == "DXT5_RGBA_BE") return makeSimple(Tag::DXT5_RGBA_BE, 5, true); if (f == "ETC1_RGB") return makeSimple(Tag::ETC1_RGB, 32); if (f == "ETC1_RGB_A8") return makeAux(Tag::ETC1_RGB, 147, AlphaScheme::A8); if (f == "ETC1_RGB_A_Palette") return makeAux(Tag::ETC1_RGB, 147, AlphaScheme::Palette4_A1, true); if (f == "PVRTC_4BPP_RGBA") return makeSimple(Tag::PVRTC_4BPP_RGBA, 30); if (f == "PVRTC_4BPP_RGBA_A8") return makeAux(Tag::PVRTC_4BPP_RGBA, 148, AlphaScheme::A8); if (f == "PVRTC_4BPP_RGBA_A_Palette") return makeAux(Tag::PVRTC_4BPP_RGBA, 148, AlphaScheme::Palette4_A1, true); if (f == "PVRTC_2BPP_RGBA") return makeSimple(Tag::PVRTC_2BPP_RGBA, 31); if (f == "ASTC_4x4") return makeSimple(Tag::ASTC_4x4, 160, false, true); if (f == "ASTC_5x5") return makeSimple(Tag::ASTC_5x5, 161, false, true); if (f == "ASTC_6x6") return makeSimple(Tag::ASTC_6x6, 162, false, true); if (f == "ASTC_8x8") return makeSimple(Tag::ASTC_8x8, 163, false, true);
 int v{}; if (f.empty() || std::from_chars(f.data(), f.data() + f.size(), v).ec != std::errc{}) return invalidSpec(); switch (v) { case 0:return makeSimple(Tag::ARGB8888,0); case 1:return makeSimple(Tag::RGBA4444,1); case 2:return makeSimple(Tag::RGB565,2); case 3:return makeSimple(Tag::RGBA5551,3); case 5:return makeSimple(Tag::DXT5_RGBA_MortonBlock,5); case 21:return makeSimple(Tag::RGBA4444_Block,21); case 22:return makeSimple(Tag::RGB565_Block,22); case 23:return makeSimple(Tag::RGBA5551_Block,23); case 30:return makeSimple(Tag::PVRTC_4BPP_RGBA,30); case 31:return makeSimple(Tag::PVRTC_2BPP_RGBA,31); case 32:return makeSimple(Tag::ETC1_RGB,32); case 35:return makeSimple(Tag::DXT1_RGB,35); case 36:return makeSimple(Tag::DXT3_RGBA,36); case 37:return makeSimple(Tag::DXT5_RGBA,37); case 147:return makeAux(Tag::ETC1_RGB,147,AlphaScheme::A8); case 148:return makeAux(Tag::PVRTC_4BPP_RGBA,148,AlphaScheme::A8); case 149:return makeAux(Tag::XRGB8888_AuxAlpha,149,AlphaScheme::A8); case 150:return makeAux(Tag::ETC1_RGB,150,AlphaScheme::A8); case 160:return makeSimple(Tag::ASTC_4x4,160,false,true); case 161:return makeSimple(Tag::ASTC_5x5,161,false,true); case 162:return makeSimple(Tag::ASTC_6x6,162,false,true); case 163:return makeSimple(Tag::ASTC_8x8,163,false,true); default:return invalidSpec(); }
}
}
}
