cmake_minimum_required(VERSION 4.3.0)
project(cpr LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_STATIC_LIBS ON CACHE BOOL "" FORCE)
set(BUILD_CURL_EXE OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(ENABLE_CURL_MANUAL OFF CACHE BOOL "" FORCE)
set(BUILD_LIBCURL_DOCS OFF CACHE BOOL "" FORCE)
set(PICKY_COMPILER OFF CACHE BOOL "" FORCE)
set(CURL_WERROR OFF CACHE BOOL "" FORCE)
set(CURL_USE_MBEDTLS ON CACHE BOOL "" FORCE)
set(CURL_USE_OPENSSL OFF CACHE BOOL "" FORCE)
set(CURL_CA_BUNDLE none CACHE STRING "" FORCE)
set(CURL_CA_PATH /system/etc/security/cacerts CACHE STRING "" FORCE)
set(CURL_DISABLE_INSTALL ON CACHE BOOL "" FORCE)
set(CURL_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(CURL_USE_PKGCONFIG OFF CACHE BOOL "" FORCE)
set(CURL_USE_CMAKECONFIG OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBPSL OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBSSH2 OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBSSH OFF CACHE BOOL "" FORCE)
set(CURL_USE_GSASL OFF CACHE BOOL "" FORCE)
set(CURL_USE_GSSAPI OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBBACKTRACE OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBUV OFF CACHE BOOL "" FORCE)
set(CURL_DISABLE_LDAP ON CACHE BOOL "" FORCE)
set(CURL_DISABLE_LDAPS ON CACHE BOOL "" FORCE)
set(USE_LIBIDN2 OFF CACHE BOOL "" FORCE)
set(USE_NGHTTP2 OFF CACHE BOOL "" FORCE)
set(CURL_BROTLI OFF CACHE BOOL "" FORCE)
set(CURL_ZSTD OFF CACHE BOOL "" FORCE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(MBEDTLS_FATAL_WARNINGS OFF CACHE BOOL "" FORCE)
set(DISABLE_PACKAGE_CONFIG_AND_INSTALL ON CACHE BOOL "" FORCE)
set(USE_STATIC_MBEDTLS_LIBRARY ON CACHE BOOL "" FORCE)
set(USE_SHARED_MBEDTLS_LIBRARY OFF CACHE BOOL "" FORCE)

find_library(log-lib log)
find_library(android-lib android)

add_subdirectory(lib/mbedtls ${CMAKE_CURRENT_BINARY_DIR}/mbedtls-build)
target_compile_definitions(mbedx509 PUBLIC MBEDTLS_FS_IO)
target_compile_definitions(mbedtls PUBLIC MBEDTLS_FS_IO)

set(MBEDTLS_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/lib/mbedtls/include)
set(MBEDTLS_LIBRARY mbedtls)
set(MBEDX509_LIBRARY mbedx509)
set(MBEDCRYPTO_LIBRARY tfpsacrypto)
set(MBEDTLS_USE_STATIC_LIBS ON)

add_subdirectory(lib/curl ${CMAKE_CURRENT_BINARY_DIR}/curl-build)

add_library(cpr_shared SHARED native-lib.cpp)
set_target_properties(cpr_shared PROPERTIES OUTPUT_NAME cpr)

target_include_directories(cpr_shared PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/lib/cpr/include
    ${CMAKE_CURRENT_SOURCE_DIR}/lib/curl/include
)

target_compile_options(cpr_shared PRIVATE
    -O3
    -DNDEBUG
    -ffunction-sections
    -fdata-sections
)

target_link_options(cpr_shared PRIVATE -Wl,--gc-sections)
target_link_libraries(cpr_shared PRIVATE libcurl ${log-lib} ${android-lib})
